[project]
name = "cursor-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.9.2",
    "numpy>=2.1.1",
    "pandas>=2.2.3",
]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
]
